### ISSUE TITLE
React-Native에서 임포트 후 빌드시 Build Fail error 발생합니다.

### ISSUE THREAD

**Issue by tjholic** [jeongjuwon/react-native-iamport#11]
/Users/kwontaejin/Documents/Git/cocktail4u-mobile-app/node_modules/react-native-iamport/ios/IAmPort/IAmPort.m:12:1: error: duplicate interface definition for class 'IAmPort'
@interface IAmPort : RCTViewManager
^
In file included from /Users/tjholic/Documents/Git/package_name/node_modules/react-native-iamport/ios/IAmPort/IAmPort.m:9:
/Users/tjholic/Documents/Git/package_name/node_modules/react-native-iamport/ios/IAmPort/IAmPort.h:12:12: note: previous definition is here
@interface IAmPort : NSObject <RCTBridgeModule>
           ^
/Users/tjholic/Documents/Git/package_name/node_modules/react-native-iamport/ios/IAmPort/IAmPort.m:29:14: error: use of undeclared identifier 'MKMapView'
    return [[MKMapView alloc] init];

The following build commands failed:
	CompileC /Users/tjholic/Documents/Git/cocktail4u-mobile-app/ios/build/Build/Intermediates.noindex/IAmPort.build/Debug-iphonesimulator/IAmPort.build/Objects-normal/x86_64/IAmPort.o IAmPort/IAmPort.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

**Comment by HongSeokHwan** [comment]
Same here!

**Comment by jangbora** [comment]
안녕하세요, 아임포트입니다. (정확한 원인을 찾지는 못하고 있습니다만) React Native 가 자동생성해내는 코드에서 스스로 오류가 발생하고 있습니다. 

1) react-native-iamport 모듈 폴더 하위에 ios > IAmPort > IAmPort.h 와 IAmPort.m 이 생겨있을텐데, 
IAmPort.m 파일에서 아래와 같이 두 줄을 주석으로 막아주셔야 합니다. 

```
//@interface IAmPort : RCTViewManager
//@end
```

2) MapKit관련 오류도 발생할텐데, IAmPort.m 파일에 아래의 import 문장을 추가해주시면 됩니다.

```
#import <MapKit/MapKit.h>
```
